name: Build, Test, Deploy

on: [push]

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Print node info
        run: |
          cat /etc/os-release
  build:
    runs-on: ubuntu-latest
    needs: info
    strategy:
      matrix:
        python-version: [ "3.10" ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          sudo apt install pycodestyle
          pip install pylint build
      - name: Build package
        run: |
          python -m build .
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: built-artifacts
          path: dist
          retention-days: 1
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt install pycodestyle
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: built-artifacts
          path: dist
      - name: Analysing the code with pycodestyle
        run: |
          ls -la
          pycodestyle src/**/*.py
