name: Build, Test, Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Print node info
        run: |
          cat /etc/os-release
  build:
    runs-on: ubuntu-latest
    needs: info
    strategy:
      matrix:
        python-version: [ "3.10" ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build package
        run: |
          python -m build .
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        # pylint $(git ls-files '*.py')
        echo "Test"
